package com.chuckanutbay.businessobjects;

// Generated Oct 18, 2010 5:44:59 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * KosherStatuses generated by hbm2java
 */
@Entity
@Table(name = "kosher_statuses", catalog = "loeppky_chuckanutbayextra")
public class KosherStatuses implements java.io.Serializable {

	private int id;
	private String description;
	private Date lastModifiedTime;

	public KosherStatuses() {
	}

	public KosherStatuses(int id, String description, Date lastModifiedTime) {
		this.id = id;
		this.description = description;
		this.lastModifiedTime = lastModifiedTime;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "description", nullable = false, length = 256)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified_time", nullable = false, length = 19)
	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

}
