package com.chuckanutbay.businessobjects;

// Generated Oct 18, 2010 5:44:59 PM by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Lotcodes generated by hbm2java
 */
@Entity
@Table(name = "lotcodes", catalog = "loeppky_chuckanutbayextra")
public class Lotcodes implements java.io.Serializable {

	private LotcodesId id;

	public Lotcodes() {
	}

	public Lotcodes(LotcodesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "lotcode", column = @Column(name = "lotcode", nullable = false, length = 50)),
			@AttributeOverride(name = "checkedInDate", column = @Column(name = "checked_in_date", nullable = false, length = 10)),
			@AttributeOverride(name = "inUseDate", column = @Column(name = "in_use_date", length = 10)),
			@AttributeOverride(name = "usedUpDate", column = @Column(name = "used_up_date", length = 10)),
			@AttributeOverride(name = "lastModifiedTime", column = @Column(name = "last_modified_time", nullable = false, length = 19)) })
	public LotcodesId getId() {
		return this.id;
	}

	public void setId(LotcodesId id) {
		this.id = id;
	}

}
