package com.chuckanutbay.businessobjects;

// Generated Oct 18, 2010 5:44:59 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LotcodesId generated by hbm2java
 */
@Embeddable
public class LotcodesId implements java.io.Serializable {

	private String lotcode;
	private Date checkedInDate;
	private Date inUseDate;
	private Date usedUpDate;
	private Date lastModifiedTime;

	public LotcodesId() {
	}

	public LotcodesId(String lotcode, Date checkedInDate, Date lastModifiedTime) {
		this.lotcode = lotcode;
		this.checkedInDate = checkedInDate;
		this.lastModifiedTime = lastModifiedTime;
	}

	public LotcodesId(String lotcode, Date checkedInDate, Date inUseDate,
			Date usedUpDate, Date lastModifiedTime) {
		this.lotcode = lotcode;
		this.checkedInDate = checkedInDate;
		this.inUseDate = inUseDate;
		this.usedUpDate = usedUpDate;
		this.lastModifiedTime = lastModifiedTime;
	}

	@Column(name = "lotcode", nullable = false, length = 50)
	public String getLotcode() {
		return this.lotcode;
	}

	public void setLotcode(String lotcode) {
		this.lotcode = lotcode;
	}

	@Column(name = "checked_in_date", nullable = false, length = 10)
	public Date getCheckedInDate() {
		return this.checkedInDate;
	}

	public void setCheckedInDate(Date checkedInDate) {
		this.checkedInDate = checkedInDate;
	}

	@Column(name = "in_use_date", length = 10)
	public Date getInUseDate() {
		return this.inUseDate;
	}

	public void setInUseDate(Date inUseDate) {
		this.inUseDate = inUseDate;
	}

	@Column(name = "used_up_date", length = 10)
	public Date getUsedUpDate() {
		return this.usedUpDate;
	}

	public void setUsedUpDate(Date usedUpDate) {
		this.usedUpDate = usedUpDate;
	}

	@Column(name = "last_modified_time", nullable = false, length = 19)
	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LotcodesId))
			return false;
		LotcodesId castOther = (LotcodesId) other;

		return ((this.getLotcode() == castOther.getLotcode()) || (this
				.getLotcode() != null && castOther.getLotcode() != null && this
				.getLotcode().equals(castOther.getLotcode())))
				&& ((this.getCheckedInDate() == castOther.getCheckedInDate()) || (this
						.getCheckedInDate() != null
						&& castOther.getCheckedInDate() != null && this
						.getCheckedInDate()
						.equals(castOther.getCheckedInDate())))
				&& ((this.getInUseDate() == castOther.getInUseDate()) || (this
						.getInUseDate() != null
						&& castOther.getInUseDate() != null && this
						.getInUseDate().equals(castOther.getInUseDate())))
				&& ((this.getUsedUpDate() == castOther.getUsedUpDate()) || (this
						.getUsedUpDate() != null
						&& castOther.getUsedUpDate() != null && this
						.getUsedUpDate().equals(castOther.getUsedUpDate())))
				&& ((this.getLastModifiedTime() == castOther
						.getLastModifiedTime()) || (this.getLastModifiedTime() != null
						&& castOther.getLastModifiedTime() != null && this
						.getLastModifiedTime().equals(
								castOther.getLastModifiedTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getLotcode() == null ? 0 : this.getLotcode().hashCode());
		result = 37
				* result
				+ (getCheckedInDate() == null ? 0 : this.getCheckedInDate()
						.hashCode());
		result = 37 * result
				+ (getInUseDate() == null ? 0 : this.getInUseDate().hashCode());
		result = 37
				* result
				+ (getUsedUpDate() == null ? 0 : this.getUsedUpDate()
						.hashCode());
		result = 37
				* result
				+ (getLastModifiedTime() == null ? 0 : this
						.getLastModifiedTime().hashCode());
		return result;
	}

}
