package com.chuckanutbay.businessobjects;

// Generated Oct 18, 2010 5:44:59 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NameImages generated by hbm2java
 */
@Entity
@Table(name = "name_images", catalog = "loeppky_chuckanutbayextra")
public class NameImages implements java.io.Serializable {

	private Integer id;
	private String name;
	private byte[] data;
	private String size;
	private Date lastModifiedTime;

	public NameImages() {
	}

	public NameImages(String name, byte[] data, String size,
			Date lastModifiedTime) {
		this.name = name;
		this.data = data;
		this.size = size;
		this.lastModifiedTime = lastModifiedTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 256)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "data", nullable = false)
	public byte[] getData() {
		return this.data;
	}

	public void setData(byte[] data) {
		this.data = data;
	}

	@Column(name = "size", nullable = false, length = 50)
	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified_time", nullable = false, length = 19)
	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

}
