package com.chuckanutbay.businessobjects;

// Generated Oct 18, 2010 5:44:59 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NutritionLabels generated by hbm2java
 */
@Entity
@Table(name = "nutrition_labels", catalog = "loeppky_chuckanutbayextra")
public class NutritionLabels implements java.io.Serializable {

	private String id;
	private int usLabelImageId;
	private Integer cdnLabelImageId;
	private String ingredients;
	private String allergens;
	private Date lastModifiedTime;

	public NutritionLabels() {
	}

	public NutritionLabels(String id, int usLabelImageId, String ingredients,
			String allergens, Date lastModifiedTime) {
		this.id = id;
		this.usLabelImageId = usLabelImageId;
		this.ingredients = ingredients;
		this.allergens = allergens;
		this.lastModifiedTime = lastModifiedTime;
	}

	public NutritionLabels(String id, int usLabelImageId,
			Integer cdnLabelImageId, String ingredients, String allergens,
			Date lastModifiedTime) {
		this.id = id;
		this.usLabelImageId = usLabelImageId;
		this.cdnLabelImageId = cdnLabelImageId;
		this.ingredients = ingredients;
		this.allergens = allergens;
		this.lastModifiedTime = lastModifiedTime;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 10)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "us_label_image_id", nullable = false)
	public int getUsLabelImageId() {
		return this.usLabelImageId;
	}

	public void setUsLabelImageId(int usLabelImageId) {
		this.usLabelImageId = usLabelImageId;
	}

	@Column(name = "cdn_label_image_id")
	public Integer getCdnLabelImageId() {
		return this.cdnLabelImageId;
	}

	public void setCdnLabelImageId(Integer cdnLabelImageId) {
		this.cdnLabelImageId = cdnLabelImageId;
	}

	@Column(name = "ingredients", nullable = false, length = 65535)
	public String getIngredients() {
		return this.ingredients;
	}

	public void setIngredients(String ingredients) {
		this.ingredients = ingredients;
	}

	@Column(name = "allergens", nullable = false, length = 65535)
	public String getAllergens() {
		return this.allergens;
	}

	public void setAllergens(String allergens) {
		this.allergens = allergens;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified_time", nullable = false, length = 19)
	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

}
