package com.chuckanutbay.businessobjects;

// Generated Oct 18, 2010 5:44:59 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QuickbooksItemSupplements generated by hbm2java
 */
@Entity
@Table(name = "quickbooks_item_supplements", catalog = "loeppky_chuckanutbayextra")
public class QuickbooksItemSupplements implements java.io.Serializable {

	private String id;
	private String tagLine;
	private String description;
	private String nameLine2;
	private String nameImageId;
	private Integer storageInfoId;
	private Integer productionCodeId;
	private Integer kosherStatusId;
	private String caseDimensions;
	private Integer casesPerPalletLayer;
	private Integer caseLayersPerPallet;
	private String productType;
	private String size;
	private Date lastModifiedTime;
	private Set<QuickbooksItems> quickbooksItemses = new HashSet<QuickbooksItems>(
			0);

	public QuickbooksItemSupplements() {
	}

	public QuickbooksItemSupplements(String id, String tagLine,
			String description, String nameLine2, String nameImageId,
			Date lastModifiedTime) {
		this.id = id;
		this.tagLine = tagLine;
		this.description = description;
		this.nameLine2 = nameLine2;
		this.nameImageId = nameImageId;
		this.lastModifiedTime = lastModifiedTime;
	}

	public QuickbooksItemSupplements(String id, String tagLine,
			String description, String nameLine2, String nameImageId,
			Integer storageInfoId, Integer productionCodeId,
			Integer kosherStatusId, String caseDimensions,
			Integer casesPerPalletLayer, Integer caseLayersPerPallet,
			String productType, String size, Date lastModifiedTime,
			Set<QuickbooksItems> quickbooksItemses) {
		this.id = id;
		this.tagLine = tagLine;
		this.description = description;
		this.nameLine2 = nameLine2;
		this.nameImageId = nameImageId;
		this.storageInfoId = storageInfoId;
		this.productionCodeId = productionCodeId;
		this.kosherStatusId = kosherStatusId;
		this.caseDimensions = caseDimensions;
		this.casesPerPalletLayer = casesPerPalletLayer;
		this.caseLayersPerPallet = caseLayersPerPallet;
		this.productType = productType;
		this.size = size;
		this.lastModifiedTime = lastModifiedTime;
		this.quickbooksItemses = quickbooksItemses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 10)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "tag_line", nullable = false, length = 256)
	public String getTagLine() {
		return this.tagLine;
	}

	public void setTagLine(String tagLine) {
		this.tagLine = tagLine;
	}

	@Column(name = "description", nullable = false, length = 256)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "name_line_2", nullable = false, length = 256)
	public String getNameLine2() {
		return this.nameLine2;
	}

	public void setNameLine2(String nameLine2) {
		this.nameLine2 = nameLine2;
	}

	@Column(name = "name_image_id", nullable = false, length = 10)
	public String getNameImageId() {
		return this.nameImageId;
	}

	public void setNameImageId(String nameImageId) {
		this.nameImageId = nameImageId;
	}

	@Column(name = "storage_info_id")
	public Integer getStorageInfoId() {
		return this.storageInfoId;
	}

	public void setStorageInfoId(Integer storageInfoId) {
		this.storageInfoId = storageInfoId;
	}

	@Column(name = "production_code_id")
	public Integer getProductionCodeId() {
		return this.productionCodeId;
	}

	public void setProductionCodeId(Integer productionCodeId) {
		this.productionCodeId = productionCodeId;
	}

	@Column(name = "kosher_status_id")
	public Integer getKosherStatusId() {
		return this.kosherStatusId;
	}

	public void setKosherStatusId(Integer kosherStatusId) {
		this.kosherStatusId = kosherStatusId;
	}

	@Column(name = "case_dimensions", length = 22)
	public String getCaseDimensions() {
		return this.caseDimensions;
	}

	public void setCaseDimensions(String caseDimensions) {
		this.caseDimensions = caseDimensions;
	}

	@Column(name = "cases_per_pallet_layer")
	public Integer getCasesPerPalletLayer() {
		return this.casesPerPalletLayer;
	}

	public void setCasesPerPalletLayer(Integer casesPerPalletLayer) {
		this.casesPerPalletLayer = casesPerPalletLayer;
	}

	@Column(name = "case_layers_per_pallet")
	public Integer getCaseLayersPerPallet() {
		return this.caseLayersPerPallet;
	}

	public void setCaseLayersPerPallet(Integer caseLayersPerPallet) {
		this.caseLayersPerPallet = caseLayersPerPallet;
	}

	@Column(name = "product_type", length = 26)
	public String getProductType() {
		return this.productType;
	}

	public void setProductType(String productType) {
		this.productType = productType;
	}

	@Column(name = "size", length = 20)
	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified_time", nullable = false, length = 19)
	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quickbooksItemSupplements")
	public Set<QuickbooksItems> getQuickbooksItemses() {
		return this.quickbooksItemses;
	}

	public void setQuickbooksItemses(Set<QuickbooksItems> quickbooksItemses) {
		this.quickbooksItemses = quickbooksItemses;
	}

}
