package com.chuckanutbay.businessobjects;

// Generated Oct 18, 2010 5:44:59 PM by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QuickbooksItems generated by hbm2java
 */
@Entity
@Table(name = "quickbooks_items", catalog = "loeppky_chuckanutbayextra")
public class QuickbooksItems implements java.io.Serializable {

	private String id;
	private QuickbooksItemSupplements quickbooksItemSupplements;
	private String description;
	private BigDecimal price;
	private String upc;
	private BigDecimal grossWeightLb;
	private int pack;
	private BigDecimal unitWeightOz;
	private Integer unitWeightG;
	private BigDecimal caseCube;
	private String nutritionLabelId;
	private Date lastModifiedTime;

	public QuickbooksItems() {
	}

	public QuickbooksItems(String id, String description, BigDecimal price,
			String upc, BigDecimal grossWeightLb, int pack,
			BigDecimal unitWeightOz, Date lastModifiedTime) {
		this.id = id;
		this.description = description;
		this.price = price;
		this.upc = upc;
		this.grossWeightLb = grossWeightLb;
		this.pack = pack;
		this.unitWeightOz = unitWeightOz;
		this.lastModifiedTime = lastModifiedTime;
	}

	public QuickbooksItems(String id,
			QuickbooksItemSupplements quickbooksItemSupplements,
			String description, BigDecimal price, String upc,
			BigDecimal grossWeightLb, int pack, BigDecimal unitWeightOz,
			Integer unitWeightG, BigDecimal caseCube, String nutritionLabelId,
			Date lastModifiedTime) {
		this.id = id;
		this.quickbooksItemSupplements = quickbooksItemSupplements;
		this.description = description;
		this.price = price;
		this.upc = upc;
		this.grossWeightLb = grossWeightLb;
		this.pack = pack;
		this.unitWeightOz = unitWeightOz;
		this.unitWeightG = unitWeightG;
		this.caseCube = caseCube;
		this.nutritionLabelId = nutritionLabelId;
		this.lastModifiedTime = lastModifiedTime;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 10)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "quickbooks_item_supplement_id")
	public QuickbooksItemSupplements getQuickbooksItemSupplements() {
		return this.quickbooksItemSupplements;
	}

	public void setQuickbooksItemSupplements(
			QuickbooksItemSupplements quickbooksItemSupplements) {
		this.quickbooksItemSupplements = quickbooksItemSupplements;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "price", nullable = false, precision = 6)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "upc", nullable = false, length = 16)
	public String getUpc() {
		return this.upc;
	}

	public void setUpc(String upc) {
		this.upc = upc;
	}

	@Column(name = "gross_weight_lb", nullable = false, precision = 6, scale = 3)
	public BigDecimal getGrossWeightLb() {
		return this.grossWeightLb;
	}

	public void setGrossWeightLb(BigDecimal grossWeightLb) {
		this.grossWeightLb = grossWeightLb;
	}

	@Column(name = "pack", nullable = false)
	public int getPack() {
		return this.pack;
	}

	public void setPack(int pack) {
		this.pack = pack;
	}

	@Column(name = "unit_weight_oz", nullable = false, precision = 5, scale = 1)
	public BigDecimal getUnitWeightOz() {
		return this.unitWeightOz;
	}

	public void setUnitWeightOz(BigDecimal unitWeightOz) {
		this.unitWeightOz = unitWeightOz;
	}

	@Column(name = "unit_weight_g")
	public Integer getUnitWeightG() {
		return this.unitWeightG;
	}

	public void setUnitWeightG(Integer unitWeightG) {
		this.unitWeightG = unitWeightG;
	}

	@Column(name = "case_cube", precision = 3)
	public BigDecimal getCaseCube() {
		return this.caseCube;
	}

	public void setCaseCube(BigDecimal caseCube) {
		this.caseCube = caseCube;
	}

	@Column(name = "nutrition_label_id", length = 10)
	public String getNutritionLabelId() {
		return this.nutritionLabelId;
	}

	public void setNutritionLabelId(String nutritionLabelId) {
		this.nutritionLabelId = nutritionLabelId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified_time", nullable = false, length = 19)
	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

}
