package com.chuckanutbay.businessobjects;

// Generated Oct 18, 2010 5:44:59 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StorageInfos generated by hbm2java
 */
@Entity
@Table(name = "storage_infos", catalog = "loeppky_chuckanutbayextra")
public class StorageInfos implements java.io.Serializable {

	private Integer id;
	private String frozenShelfLife;
	private String frozenTemperatureRange;
	private String refrigeratedShelfLife;
	private String refrigeratedTemperatureRange;
	private String roomShelfLife;
	private String roomTemperatureRange;
	private Date lastModifiedTime;

	public StorageInfos() {
	}

	public StorageInfos(String frozenShelfLife, String frozenTemperatureRange,
			String refrigeratedShelfLife, String refrigeratedTemperatureRange,
			String roomShelfLife, String roomTemperatureRange,
			Date lastModifiedTime) {
		this.frozenShelfLife = frozenShelfLife;
		this.frozenTemperatureRange = frozenTemperatureRange;
		this.refrigeratedShelfLife = refrigeratedShelfLife;
		this.refrigeratedTemperatureRange = refrigeratedTemperatureRange;
		this.roomShelfLife = roomShelfLife;
		this.roomTemperatureRange = roomTemperatureRange;
		this.lastModifiedTime = lastModifiedTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "frozen_shelf_life", nullable = false, length = 16)
	public String getFrozenShelfLife() {
		return this.frozenShelfLife;
	}

	public void setFrozenShelfLife(String frozenShelfLife) {
		this.frozenShelfLife = frozenShelfLife;
	}

	@Column(name = "frozen_temperature_range", nullable = false, length = 16)
	public String getFrozenTemperatureRange() {
		return this.frozenTemperatureRange;
	}

	public void setFrozenTemperatureRange(String frozenTemperatureRange) {
		this.frozenTemperatureRange = frozenTemperatureRange;
	}

	@Column(name = "refrigerated_shelf_life", nullable = false, length = 16)
	public String getRefrigeratedShelfLife() {
		return this.refrigeratedShelfLife;
	}

	public void setRefrigeratedShelfLife(String refrigeratedShelfLife) {
		this.refrigeratedShelfLife = refrigeratedShelfLife;
	}

	@Column(name = "refrigerated_temperature_range", nullable = false, length = 16)
	public String getRefrigeratedTemperatureRange() {
		return this.refrigeratedTemperatureRange;
	}

	public void setRefrigeratedTemperatureRange(
			String refrigeratedTemperatureRange) {
		this.refrigeratedTemperatureRange = refrigeratedTemperatureRange;
	}

	@Column(name = "room_shelf_life", nullable = false, length = 16)
	public String getRoomShelfLife() {
		return this.roomShelfLife;
	}

	public void setRoomShelfLife(String roomShelfLife) {
		this.roomShelfLife = roomShelfLife;
	}

	@Column(name = "room_temperature_range", nullable = false, length = 16)
	public String getRoomTemperatureRange() {
		return this.roomTemperatureRange;
	}

	public void setRoomTemperatureRange(String roomTemperatureRange) {
		this.roomTemperatureRange = roomTemperatureRange;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified_time", nullable = false, length = 19)
	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

}
